config/routes.rb
Rails.application.routes.draw do

 scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :items, only: [:index, :show]

  scope do
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  get '/customers/my_page' => 'customers#show'
  get '/customers/cunfirm' => 'customers#confirm'
  resources :customers, only: [:edit, :update] do
    collection do
      patch 'withdraw'
      get 'confirm'
    end

  end

  resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete 'empty'
    end
  end

  resources :orders, only: [:show, :index, :new, :create] do
    collection do
      post 'confirm'
      get 'thanks'
    end
  end
end

     #devise_for  :members #devise_for  :users
    devise_for :admins, :controllers => {:registrations => 'admin/admins/registrations', :sessions => 'admin/admins/sessions' }
    devise_for :customers, :controllers => {:registrations => 'public/customers/registrations', :sessions => 'public/customers/sessions' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  namespace :admin do
    root to: 'homes#top'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, :address, :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

   def active_for_authentication?
    super && (self.is_active == true)
   end


  def full_name
    first_name + last_name
  end

  acts_as_paranoid


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_items
  attachment :image
  belongs_to :genre

    enum is_active: { on_sale: 0, off_sale: 1 }

    

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items 
  
  
  belongs_to :customer
  
  enum payment_method: { credit: 0, bunk: 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { "製作不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
 before_action :authenticate_admin!

  def index
    @customers = Customer.with_deleted
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private

  def customer_params
     params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :full_name, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 


 before_action :configure_permitted_parameters, if: :devise_controller?
 
 

   def after_sign_in_path_for(resource)
      if current_customer
         root_path
      else Admin
          admin_root_path
      end
   end


    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :customer
          root_path
        elsif resource_or_scope == :admin
          admin_session_path
        end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,
                                                           :last_name,
                                                           :first_name_kana,
                                                           :last_name_kana,
                                                           :email,
                                                           :postal_code,
                                                           :address,
                                                           :telephone_number])

    end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h1><%= @customer.full_name %>さんの会員情報編集</h1>
        <div id="error_explanation">
            <% if @customer.errors.any? %>
          <h3><%= @customer.errors.count %>errors prohibited this obj from being saved:</h3>
          <% @customer.errors.full_messages.each do |message| %>
        　　<li><%= message %></li>
          <% end %>
        <% end %>

        <%= form_with model: @customer, url: admin_customer_path(@customer), local: true do |f| %>
         <table class="table table-borderless">
           <tr>
              <th class="col-xs-2">会員ID</th>
              <td class="col-xs-10"><%= @customer.id %></td>
           </tr>

           <div class="form-group">
            <tr>
              <th for="inputName">氏名</th>
              <td>
                <%= f.text_field :first_name, autofocus: true, id:"inputFirst_name", placeholder:"姓" %>　<%= f.text_field :last_name, autofocus: true, id:"inputLast_name", placeholder:"名" %>
              </td>
            </tr>
           </div>

           <div class="form-group">
            <tr>
              <th>フリガナ</th>
              <td>
                <%= f.text_field :first_name_kana, autofocus: true, id:"inputFirst_name_kana", placeholder:"セイ" %> <%= f.text_field :last_name_kana, autofocus: true, id:"inputLast_name_kana", placeholder:"メイ" %>
              </td>
            </tr>
           </div>

           <div class="form-group">
            <tr>
             <th for="inputPostal_code">郵便番号</th>
             <td>
               <%= f.text_field :postal_code, autofocus: true, id:"inputPostal_code", placeholder:"郵便番号" %>
             </td>
            </tr>
           </div>

           <div class="form-group">
            <tr>
              <th for="inputAddress">住所</th>
              <td>
                <%= f.text_field :address, autofocus: true, id:"inputAddress", placeholder:"住所" %>
              </td>
            </tr>
           </div>

           <div class="form-group">
            <tr>
              <th for="inputTelephone_number">電話番号</th>
              <td>
                <%= f.text_field :telephone_number, autofocus: true, id:"inputTelephone_number", placeholder:"電話番号" %>
              </td>
            </tr>
           </div>

           <div class="form-group">
            <tr>
              <th for="inputEmail">メールアドレス</th>
              <td>
                <%= f.text_field :email, autofocus: true, id:"inputEmail", placeholder:"メールアドレス" %>
              </td>
            </tr>
           </div>

           <div class="form-group has-icon">
             <tr>
               <th>会員ステータス</th>
               <td>
                 <%= f.radio_button :is_active, :on_sale %>
              　　 <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
              　　 <%= f.radio_button :is_active, :off_sale %>
              　　 <%= f.label :is_active, "無効", {value: :false, style: "display: inline-block;"} %>
               </td>
             </tr>
           </div>

           <div class="form-group">
             <th></th>
             <td>
               <%= f.submit "変更を保存", class: "btn btn-success d-flex align-items-end" %>
             </td>
           </div>

        </div>


        <% end %>

</div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>会員一覧</h2>
      
      <table class="table table-hover table-inverse">
          <thead>
            <tr class="table-secondary">
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
      　　　<% @customers.each do |customer| %>
      　　　<tr>
      　　　  <td><%= customer.id %></td>
      　　　  <td><%= link_to customer.full_name, admin_customer_path(customer)%></td>
      　　　  <td><%= customer.email %></td>
      　　   <td><%= customer.is_active %></td>
      　　　</tr>
      　　　<% end %>
　　</div>　
　</div>　　
</div>

app/views/admin/customers/show.html.erb
<div class="container">

  <div class="row">
   <div class="col-xs-10 col-xs-offset-1">
    <h3><%= @customer.full_name %>さんの会員詳細</h3>

     <table class="table table-borderless">

      <tr>
       <th class="col-xs-2">会員ID</th>
       <td class="col-xs-10"><%= @customer.id %></td>
      </tr>

      <tr>
       <th class="col-xs-2">氏名</th>
       <td class="col-xs-10"><%= @customer.first_name %> <%= @customer.last_name %></td>
      </tr>

      <tr>
       <th class="col-xs-2">フリガナ</th>
       <td class="col-xs-10"><%= @customer.first_name_kana %> <%= @customer.last_name_kana %></td>
      </tr>

      <tr>
       <th class="col-xs-2">郵便番号</th>
       <td class="col-xs-10"><%= @customer.postal_code %></td>
      </tr>

      <tr>
       <th class="col-xs-2">住所</th>
       <td class="col-xs-10"><%= @customer.address %></td>
      </tr>

      <tr>
       <th class="col-xs-2">電話番号</th>
       <td class="col-xs-10"><%= @customer.telephone_number %></td>
      </tr>

      <tr>
       <th class="col-xs-2">メールアドレス</th>
       <td class="col-xs-10"><%= @customer.email %></td>
      </tr>

      <tr>
       <th class="col-xs-2">会員ステータス</th>
       <td class="col-xs-10"><%= @customer.is_active %></td>
      </tr>

     </table>

   </div>
  </div>

     <div class="form-group row justify-content-center">
      <div>
       <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>

       <%= link_to "注文履歴一覧を見る",admin_root_path, class: "btn btn-primary" %>
      </div>
     </div>
</div>

app/views/customers/confirm.html.erb
<label>本当に退会しますか？</label>
<p>退会すると、会員登録情報や</p><br>
<p>これまでの購入履歴が閲覧できなくなります。</p><br>
<p>退会する場合は、「退会する」をクリックしてください。</p>
 <%= link_to "退会しない", customers_my_page_path(@customer), class: "btn btn-sm btn-success" %>  <%= link_to "退会する", withdraw_customers_path(@customer), class: "btn btn-sm btn-success" %>