config/routes.rb
Rails.application.routes.draw do

 scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :items, only: [:index, :show]

  scope do
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  get '/customers/my_page' => 'customers#show'
  get '/customers/cunfirm' => 'customers#confirm'
  resources :customers, only: [:edit, :update] do
    collection do
      patch 'withdraw'
      get 'confirm'
    end

  end

  resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete 'empty'
    end
  end

  resources :orders, only: [:show, :index, :new, :create] do
    collection do
      post 'confirm'
      get 'thanks'
    end
  end
end

     #devise_for  :members #devise_for  :users
    devise_for :admins, :controllers => {:registrations => 'admin/admins/registrations', :sessions => 'admin/admins/sessions' }
    devise_for :customers, :controllers => {:registrations => 'public/customers/registrations', :sessions => 'public/customers/sessions' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  namespace :admin do
    root to: 'homes#top'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, :address, :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

   def active_for_authentication?
    super && (self.is_active == true)
   end


  def full_name
    first_name + last_name
  end

  acts_as_paranoid


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_items
  attachment :image
  belongs_to :genre

    enum is_active: { on_sale: 0, off_sale: 1 }

    

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items 
  
  
  belongs_to :customer
  
  enum payment_method: { credit: 0, bunk: 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { "製作不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
   before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    #商品合計
    @total = 0
    @order_items.each do |order_item|
      tol = order_item.item.price * order_item.amount.to_i
      @total += tol 
    end
  end
  
  def update
    order = Order.find(params[:id])
    #注文ステータスが"入金確認"になったら製作ステータスを"製作待ち"
    if params[:order][:status] == "b"
      order.order_items.each do |order_item|
        order_item.making_status = "b"
        order_item.update(making_status: order_item.making_status)
      end
    end
    order.update(order_params)
    redirect_to admin_order_path(order)
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 


 before_action :configure_permitted_parameters, if: :devise_controller?
 
 

   def after_sign_in_path_for(resource)
      if current_customer
         root_path
      else Admin
          admin_root_path
      end
   end


    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :customer
          root_path
        elsif resource_or_scope == :admin
          admin_session_path
        end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,
                                                           :last_name,
                                                           :first_name_kana,
                                                           :last_name_kana,
                                                           :email,
                                                           :postal_code,
                                                           :address,
                                                           :telephone_number])

    end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
  　<h2>注文履歴詳細</h2>
    　<div class="col-md-10 col-md-offset-1">


        <div class="col-md-7 h5">

          <table class="table table-borderless">
            <tr>
              <th>購入者</th>
              <td><%= link_to @order.customer.full_name, admin_customer_path(@order) %></td>
            </tr>

            <tr>
              <th>注文日</th>
              <td><%= @order.created_at.strftime("%Y/%-m/%-d") %></td>
            </tr>

            <tr>
              <th>配送先</th>
              <td>〒<%= @order.postal_code %><%= @order.address %><br>
                  <%= @order.name %>
              </td>
            </tr>

            <tr>
              <th>支払方法</th>
              <td><%= @order.payment_method %></td>
            </tr>

            <tr>
              <th>ステータス</th>
              <td>
              <%= form_with model: @order, url: admin_order_path(@order), local: true do |f| %>
              <%= f.select :status, Order.statuses.keys.to_a %>
              <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
              </td>
            </tr>

            </tbody>
          </table>
          </div>
          <div class="row">

           <div class="col-md-8">
            <table class="table table-bordered">
              <thead class="table-secondary">
                <tr>
                  <th>商品名</th>
                  <th>単価（税込）</th>
                  <th>数量</th>
                  <th>小計</th>
                </tr>
              </thead>

              <tbody>
                <% @order_items.each do |order_item| %>
                <tr>
                  <td><%= order_item.item.name %></td>
                  <td><%= (order_item.tax_price).floor.to_s(:delimited, delimiter: ',') %></td>
                  <td><%= order_item.amount %></td>
                  <td><%= (order_item.tax_price * order_item.amount.to_i).floor.to_s(:delimited, delimiter: ',') %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <div class="col-md-4 h5">

            <table class="table table-borderless">
                <tr>
                  <th>商品合計</th>
                  <td><% @sum = 0 %>
                      <% @order.order_items.each do |order_item| %>
                      <% @sum += order_item.tax_price* order_item.amount.to_i  %>
                    <% end %>
                    <%= @sum.to_s(:delimited, delimiter: ',') %>円</td>
                </tr>

                <tr>
                  <th>配送料</th>
                  <td><%= @order.postage.to_s(:delimited, delimiter: ',') %>円</td>
                </tr>

                <tr>
                  <th>請求合計金額</th>
                  <td><%= (@sum += @order.postage).to_s(:delimited, delimiter: ',') %>円</td>
                </tr>

            </table>
          </div>
          </div>

    </div>
  </div>
</div>