config/routes.rb
Rails.application.routes.draw do

 scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :items, only: [:index, :show]

  scope do
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  get '/customers/my_page' => 'customers#show'
  get '/customers/cunfirm' => 'customers#confirm'
  resources :customers, only: [:edit, :update] do
    collection do
      patch 'withdraw'
      get 'confirm'
    end

  end

  resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete 'empty'
    end
  end

  resources :orders, only: [:show, :index, :new, :create] do
    collection do
      post 'confirm'
      get 'thanks'
    end
  end
end

     #devise_for  :members #devise_for  :users
    devise_for :admins, :controllers => {:registrations => 'admin/admins/registrations', :sessions => 'admin/admins/sessions' }
    devise_for :customers, :controllers => {:registrations => 'public/customers/registrations', :sessions => 'public/customers/sessions' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  namespace :admin do
    root to: 'homes#top'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, :address, :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

   def active_for_authentication?
    super && (self.is_active == true)
   end


  def full_name
    first_name + last_name
  end

  acts_as_paranoid


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_items
  attachment :image
  belongs_to :genre

    enum is_active: { on_sale: 0, off_sale: 1 }

    

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items 
  
  
  belongs_to :customer
  
  enum payment_method: { credit: 0, bunk: 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { "製作不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 


 before_action :configure_permitted_parameters, if: :devise_controller?
 
 

   def after_sign_in_path_for(resource)
      if current_customer
         root_path
      else Admin
          admin_root_path
      end
   end


    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :customer
          root_path
        elsif resource_or_scope == :admin
          admin_session_path
        end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,
                                                           :last_name,
                                                           :first_name_kana,
                                                           :last_name_kana,
                                                           :email,
                                                           :postal_code,
                                                           :address,
                                                           :telephone_number])

    end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="d-flex flex-column p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

      <nav class="navbar navbar-expand-lg ">
        <div class="container">
          <%= link_to "秘密のケーキ屋さん", root_path, class: "h4 my-0 me-md-auto fw-normal" %>

         

          <ul class="navbar-nav ml-auto">

            <% if customer_signed_in? %>

            <li class="p-2 nav-items text-right">
              <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-secondary" %>
            </li>

            <li class="p-2 nav-items text-right">
              <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
            </li>

            <li class="p-2 nav-items text-right">
              <%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary" %>
            </li>

            <li class="p-2 nav-items text-right">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary" %>
            </li>

            <% elsif admin_signed_in? %>

            <li class="p-2 nav-items text-right">
              <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary text-right" %>
            </li>

            <li class="p-2 nav-items text-right">
              <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary" %>
            </li>

            <li class="p-2 nav-items text-right">
              <%= link_to "注文履歴一覧",admin_root_path, class: "btn btn-outline-secondary" %>
            </li>

            <li class="p-2 nav-items text-right">
              <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary" %>
            </li>

            <li class="p-2 nav-items text-right">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" %>
            </li>

            <% else %>

            <li class="p-2 nav-items text-right">
              <%= link_to "About", about_path, class: "btn btn-outline-secondary" %>
            </li>

            <li class="p-2 nav-items text-right">
              <%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
            </li>

            <li class="p-2 nav-items text-right">
              <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary" %>
            </li>

            <li class="p-2 nav-items text-right">
              <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary" %>
            </li>
            <% end %>
          </ul>
          
        </div>
      </nav>
    </header>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>